### ISSUE TITLE
authenticateAccount failing if cache enabled?

### ISSUE THREAD

**Issue by havocp** [stormpath/stormpath-sdk-java#14] opened 2013-08-27 21:27 UTC
```
Caused by: java.lang.IllegalArgumentException: Resource data must be materialized to be cached (need more than just an 'href' attribute).
at com.stormpath.sdk.lang.Assert.isTrue(Assert.java:33) ~[stormpath-sdk-api-0.8.0.jar:0.8.0]
at com.stormpath.sdk.impl.ds.DefaultDataStore.cache(DefaultDataStore.java:329) ~[stormpath-sdk-impl-0.8.0.jar:0.8.0]
at com.stormpath.sdk.impl.ds.DefaultDataStore.save(DefaultDataStore.java:263) ~[stormpath-sdk-impl-0.8.0.jar:0.8.0]
at com.stormpath.sdk.impl.ds.DefaultDataStore.create(DefaultDataStore.java:230) ~[stormpath-sdk-impl-0.8.0.jar:0.8.0]
at com.stormpath.sdk.impl.authc.BasicAuthenticator.authenticate(BasicAuthenticator.java:65) ~[stormpath-sdk-impl-0.8.0.jar:0.8.0]
at com.stormpath.sdk.impl.application.DefaultApplication.authenticateAccount(DefaultApplication.java:183) ~[stormpath-sdk-impl-0.8.0.jar:0.8.0]
```

**Comment by tusharkadm** [comment] 2015-01-08 14:02
I am getting the same error while verifying email ... Below is my code to verifyemail
 com.stormpath.sdk.account.Account account = stormpathClient.getCurrentTenant().verifyAccountEmail(token);

Error :- WARNING: Resource data must be materialized to be cached (need more than just an 'href' attribute).
java.lang.IllegalArgumentException: Resource data must be materialized to be cached (need

I am using  stormpath sdk version 1.0.RC2.1

please help me in this

**Comment by lhazlewood** [comment] 2015-01-08 17:36
@antollinim Could you please take a look at this asap?

**Comment by antollinim** [comment] 2015-01-08 19:49
Hello @tusharkadm. I am sorry to hear that you have stumbled into that (already solved) issue.
Please update the Java SDK to 1.0.RC3.preview.0. It has been solved in that version.
Regards!

**Comment by antollinim** [comment] 2015-01-08 19:49
Closing as a duplicate of https://github.com/stormpath/stormpath-sdk-java/issues/60

**Comment by antollinim** [comment] 2015-01-08 19:49
Closing as a duplicate of https://github.com/stormpath/stormpath-sdk-java/issues/60

**Closed by antollinim** 2015-01-08 19:49 UTC
Labels: bug
