### ISSUE TITLE
group custom data value removal sometimes not applied

### ISSUE THREAD

**Issue by francisdb** [stormpath/stormpath-sdk-java#637] opened 2016-05-18 13:37 UTC
Hi,

Since this morning we have tests failing that checks that modifications to custom data are applied. Not sure I should create a ticket here or on the general issue tracker.

how to reproduce:

1. get group custom data
2. add value x
3. save custom data
4. get group custom data
5. remove value x
6. save custom data
7. get group custom data

--> the value sometimes is still in the map

Scala test code below
```scala
package foobar

import com.stormpath.sdk.api.ApiKeys
import com.stormpath.sdk.application.{ApplicationCriteria, Applications}
import com.stormpath.sdk.client.Clients
import com.stormpath.sdk.directory.CustomData
import com.stormpath.sdk.group.{Group, Groups}
import org.specs2.mutable.Specification

import scala.collection.JavaConverters._


class StormpathIssueSpec extends Specification{

  "stormpath" should {

    "correctly update group custom settings" in {

      val apiKey = xxx
      val cm = new DisabledCacheManager()
      val client = Clients.builder().setApiKey(apiKey).setCacheManager(cm).build()


      for(i <- 1 to 10) {
        println(i)
        val application = client.getApplications(
          Applications.where(Applications.name().eqIgnoreCase("myApp"))
        ).single()

        val group = client.instantiate(classOf[Group])
        group.setName("foobar")
        val createdGroupd = application.createGroup(group)
        try {
          val customData = group.getCustomData
          customData.put("testkey", "testvalue")
          customData.save()
          val customData2 = client.getResource(group.getCustomData.getHref, classOf[CustomData])
          customData2.asScala.filterKeys(_.startsWith("test")) must be equalTo Map("testkey" -> "testvalue")
          customData2.remove("testkey")
          customData2.save()
          eventually {
            println("check")
            val customData3 = client.getResource(group.getCustomData.getHref, classOf[CustomData])
            customData3.asScala.filterKeys(_.startsWith("test")) must be equalTo Map()
          }
        } finally {
          createdGroupd.delete()
        }
      }

      success
    }
  }
}
```
output for a failing run:
first iteration works, second one fails

```
1
check
2
check
check
...
check
check
[info] StormpathIssueSpec
[info]
[info] stormpath should
[error]   x correctly update group custom settings
[error]    Map(testkey -> testvalue) is not equal to Map() (StormpathIssueSpec.scala:49)
[info]
```

**Comment by mrioan** [comment] 2016-05-20 14:50
Hello @francisdb 

I could not reproduce what you are experiencing. I ran an analogous code in Java but in a loop with 100 iterations.

```
for(int i = 0; i < 100; i++) {
            System.out.println(i);
            Group group = client.instantiate(Group.class);
            group.setName("foobar");
            group = application.createGroup(group);
            try {
                CustomData customData = group.getCustomData();
                customData.put("testkey", "testvalue");
                customData.save();
                CustomData customData2 = client.getResource(group.getCustomData().getHref(), CustomData.class);
                Assert.isTrue(customData2.get("testkey").equals("testvalue"));
                customData2.remove("testkey");
                customData2.save();
                System.out.println("check");
                CustomData customData3 = client.getResource(group.getCustomData().getHref(), CustomData.class);
                Assert.isTrue(customData3.get("testkey") ==  null);
            } finally {
                group.delete();
            }
        }
```

What version of our Java SDK are you using? I used our latest one: `1.0.RC9.2`

**Comment by francisdb** [comment] 2016-05-20 15:07
yes, latest version, could also have been a glitch on your backend?

**Comment by francisdb** [comment] 2016-05-20 15:08
Will try if I still have this.

**Comment by dogeared** [comment] 2016-05-23 13:54
Hey @francisdb - I believe we've addressed the issue. We found that there was a drift on one of our NTP servers that was causing intermittent write rejections for CustomData. **Note**: As far as we can tell, the custom data *was* in fact written by other nodes - just one node was rejecting the write because of the time drift. We do not believe that there was any data loss while this issue occurred and it should be completely resolved now. Please confirm and then we will close this issue. Thanks!

**Comment by francisdb** [comment] 2016-05-23 22:41
@dogeared this is indeed fixed, I can't reproduce this any more with my test.

**Closed** 2016-05-23 22:42 UTC
Labels: backlog
