### ISSUE TITLE
Account details not updated in cache.

### ISSUE THREAD

**Issue by demboos** [stormpath/stormpath-sdk-java#520] opened 2016-03-10 15:40 UTC
Hi,
I'm using Stormpath SDK 1.0.RC8.3 on a spring-boot app.

I've got some caching issues with the following scenario:

1. create an account with application.createAccount (the account is pending email verification)
2. verify the account with the token using client.verifyAccountEmail(sptoken)
3. update given name and surname on the account returned from step 2
4. call account.saveWithResponseOptions(Accounts.options().withCustomData())

5. log into my spring-boot app, retrieve account from Spring security context:
String href = ((StormpathUserDetails) SecurityContextHolder.getContext().getAuthentication().getPrincipal()).getProperties().get("href");

Account account = client.getResource(href, Account.class);

6. The account still has old given name and surname.
7. The account has proper (new) name and surname in Stormpath console.

**Comment by dogeared** [comment] 2016-03-14 03:27
Hi @demboos:

Thanks for reporting this. Please email the content of this issue to: `support@stormpath.com.`

We'll look at it right away. If we uncover a bug, we'll add it to our upcoming release and send the issue to you so you can track it.

**Comment by mrioan** [comment] 2016-03-14 16:57
Hello @demboos are you using different `Client` instances? I mean, from 1-4 it seems that you are using plain Java SDK. In 5 it seems you are using another instance of our SDK inside a Spring Boot project. Am I right? 

If that is the case you need to know that our SDK works by modifying data that actually resides in our Backend. The SDK does not have a state per-se but it does keep data in a cache in order to improve processing speed. This volatile state is not shared in different processes/jvms/servers. Each process will have its own independent state, all of them modifying the same data in Stormpath's backend but that data is not proactively pushed to the SDK in any way. The data is only updated locally after write operations or cache timeouts (the backend never PUSHES data to the clients, the client has to PULL it instead). Stormpath's backend will not lose any data when different clients are modifying it, but they will eventually lose synchronicity among them from time to time. 

For example, let's suppose you have two independent apps: app1 and app2. If app1 modifies the custom data (or any other resource) then the updated data will be seen by app1 but not by app2 yet. App2 will get the updated data only when its own cache gets invalidated or when app2 writes its own data and saves it. Only at that point the returned data will contain the changes from app2 and also the previous ones by app1.

You need to think of our UI as an additional client. If your Java App has already retrieved a resource (like custom data) and then you modify it in the UI, the Java SDK will not see the change until you retrieve the resource again (either by doing a `save()` or by invalidating the cache).

If you want to keep consistency among different processes/JVMs/servers then you need to configure a clustered cache like Hazelcast or Ehcache and have each Java SDK Instance connected to it.

**Comment by dogeared** [comment] 2016-03-15 11:11
@demboos:

One thing I want to add to what @mrioan is saying is that if you are indeed using different VM's in your scenario, the SDK supports dropping in distributed cache managers, such as hazelcast and redis. Basically, any cacheing platform that supports the `CacheManager` interface can supplant the built in cache, which is intended for single VM environments.

**Comment by demboos** [comment] 2016-03-15 11:20
Hi,

I'm using a single client, in both cases the client injected by Spring context. 

For point 1) I create an account using the client API, which triggers the verification email to be sent. Having received the verification email, the user clicks a link, which is handled by my own controller, which does points 2) and 3). Then the user is presented with Stormpath login screen where he enters the new password, he is able to log into succesfully, but I want to display his name (from the Account), so I try to retrieve it in 5) by the href stored on user details.

It all happens in one Java VM, under Spring Boot app with standard Spring cache setup.

**Comment by demboos** [comment] 2016-03-16 10:49
I looked quickly at WriteCacheFilter, it seems the cache writer is not caching when doing an "expanded" query (which I guess account.saveWithResponseOptions(Accounts.options().withCustomData()) exactly is). 

But the account might still be in cache (from previous operations), and when I execute step 5)
```
Account account = client.getResource(href, Account.class);
```
I might get the cached (previous) value? Shouldn't then the cache be cleared in case of a write operation that bypasses the cache write ?

**Comment by mrioan** [comment] 2016-03-23 21:05
I have been able to reproduce this issue. It gets fixed with #524

**Closed** 2016-03-25 02:44 UTC
Labels: bug, needs review
