### ISSUE TITLE
In sendVerificationEmail(), account store is *not* optional

### ISSUE THREAD

**Issue by chrylis** [stormpath/stormpath-sdk-java#255] opened 2015-08-11 06:39 UTC
The documentation for `Application#sendVerificationEmail()` clearly states (and the implementation in `DefaultApplication` anticipates) that the account store can be omitted to use defaults. However, actually doing this results in an HTTP 400 from the REST API:

```
Caused by: com.stormpath.sdk.resource.ResourceException: HTTP 400, Stormpath 2014 (http://docs.stormpath.com/errors/2014): accountStore property is an invalid reference.
	at com.stormpath.sdk.impl.ds.DefaultDataStore.execute(DefaultDataStore.java:474)
	at com.stormpath.sdk.impl.ds.DefaultDataStore.access$000(DefaultDataStore.java:67)
	at com.stormpath.sdk.impl.ds.DefaultDataStore$2.filter(DefaultDataStore.java:372)
	at com.stormpath.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:47)
	at com.stormpath.sdk.impl.ds.ProviderAccountResultFilter.filter(ProviderAccountResultFilter.java:31)
	at com.stormpath.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52)
	at com.stormpath.sdk.impl.ds.api.ApiKeyQueryFilter.filter(ApiKeyQueryFilter.java:74)
	at com.stormpath.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52)
	at com.stormpath.sdk.impl.ds.cache.WriteCacheFilter.filter(WriteCacheFilter.java:78)
	at com.stormpath.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52)
	at com.stormpath.sdk.impl.ds.cache.ReadCacheFilter.filter(ReadCacheFilter.java:61)
	at com.stormpath.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52)
	at com.stormpath.sdk.impl.ds.api.DecryptApiKeySecretFilter.filter(DecryptApiKeySecretFilter.java:62)
	at com.stormpath.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52)
	at com.stormpath.sdk.impl.ds.EnlistmentFilter.filter(EnlistmentFilter.java:42)
	at com.stormpath.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52)
	at com.stormpath.sdk.impl.ds.DefaultDataStore.save(DefaultDataStore.java:393)
	at com.stormpath.sdk.impl.ds.DefaultDataStore.create(DefaultDataStore.java:311)
	at com.stormpath.sdk.impl.application.DefaultApplication.sendVerificationEmail(DefaultApplication.java:570)
```

**Comment by dogeared** [comment] 2015-08-11 17:10
Confirmed.

When `setAccountStore(dir)` is commented out below, you get the 400 error. Looking into it.

```
public class StormMetal {
    public static final String DIRECTORY = "https://api.stormpath.com/v1/directories/7WCxQnStGAWTvxmJEdyKl2";
    public static final String APPLICATION = "https://api.stormpath.com/v1/applications/7WCXUThn8hhE4pFV0r9KRY";
    public static final String EMAIL = "micah+timmy@stormpath.com";

    public static void main(String[] args) {
        ClientBuilder builder = Clients.builder();
        Client client = builder.build();

        Directory dir = client.getResource(DIRECTORY, Directory.class);
        Application application = client.getResource(APPLICATION, Application.class);

        VerificationEmailRequest verificationEmailRequest = Applications.verificationEmailBuilder()
            .setLogin(EMAIL)
//            .setAccountStore(dir)
            .build();
        application.sendVerificationEmail(verificationEmailRequest);
    }
}
```

**Comment by dogeared** [comment] 2015-08-11 20:08
root cause is this is being passed over the wire:

```
"{"login":"micah+timmy@stormpath.com","accountStore":null}"
```

It should be:

```
"{"login":"micah+timmy@stormpath.com"}"
```

Working on fix now.

**Comment by dogeared** [comment] 2015-08-12 02:11
PR is up, all tests passing. Awaiting review: https://github.com/stormpath/stormpath-sdk-java/pull/256

**Comment by maranai** [comment] 2015-08-12 16:14
@dogeared I've reviewed the code changes the fix looks good, so it's approved. You can merge.

**Comment by lhazlewood** [comment] 2015-08-12 17:30
Merged - thanks!

**Closed by lhazlewood** 2015-08-12 17:30 UTC
