### ISSUE TITLE
Changes to group membership require forced logout/login to be seen in Authentication token

### ISSUE THREAD

**Issue by george-hawkins-aa** [stormpath/stormpath-sdk-java#369] opened 2015-11-24 15:21 UTC
Adding or removing a user from a group in easy using the Stormpath Java SDK.

However any such changes won't be picked up by e.g. `@PreAuthorize` checks - unless you force the user to log out and log back in.

This is because the collection of authorities that are checked by `@PreAuthorize` etc. are only built up once on login.

This means modelling e.g. "upgrade" for a user account as the joining of a Stormpath group requires what for the end user must seem like an unexpected logout step in a process that's supposed to link them tighter to ones site - not kick them out.

I've put [a project](https://github.com/george-hawkins-aa/stormpath-spring-boot-example) up on Github that demonstrates this issue. See the [dynamic groups and static authorities section](https://github.com/george-hawkins-aa/stormpath-spring-boot-example#dynamic-groups-and-static-authorities) of the README for the details and some proposed solutions.

**Comment by dogeared** [comment] 2015-11-26 06:45
Hi George:

I will definitely take a look at your project. We bumped into this at the same time, it seems.

I recently pushed up a [repo](https://github.com/stormpath/stormpath-spring-boot-fun-with-custom-data-sample) for an upcoming blog post. It's mainly about working with CustomData, but along the way I wanted to show how things work with Stormpath Groups.

I set it up so that after you registered, you could add yourself to a User Group. And, I immediately ran into the same issue you are talking about above.

I found a solution which you can see [here](https://github.com/stormpath/stormpath-spring-boot-fun-with-custom-data-sample/blob/master/src/main/java/com/stormpath/tutorial/service/GroupService.java#L59)

This refreshes the granted authorities and sets a new Authentication in the SecurityContextHolder. It does this without having to hold onto the password, which would definitely not be a good practice.

Of course, we'd like this to be managed in the SDK and not left to the user to manually include. Perhaps with some AOP around group operations? @mrioan and I were discussing the other day. Not sure what approach we will take, but definitely needed for the 1.0 release.

@lhazlewood will be interested in this too.

**Comment by george-hawkins-aa** [comment] 2015-11-26 15:22
Thanks @dogeared - your solution is cool - much simper than I expected would be needed.

I created a slightly more generic version of your `GroupService` that you can see [here](https://github.com/george-hawkins-aa/stormpath-spring-boot-example/blob/master/src/main/java/hello/GroupService.java) - unfortunately it has to use reflection to get at a currently `protected` Stormpath method. And you can see it in action at the bottom of [`HelloController`](https://github.com/george-hawkins-aa/stormpath-spring-boot-example/blob/master/src/main/java/hello/HelloController.java).

I've tried it out with all my restriction checks and it works perfectly - thanks :smile:

**Comment by mzumbadoate** [comment] 2016-08-25 20:59
@george-hawkins-aa is this still relevant?
can you provide steps to reproduce this
I'm using your project and when I add/ remove groups in api.stormpath.com I can see the group is added in /groups without the need of logout/login

**Comment by mzumbadoate** [comment] 2016-08-25 22:17
@george-hawkins-aa also, if I upgrade to Stormpath 1.0.3
using the example spring-boot-default I simply copy pasted groups.html and GroupsController, building and running the example I can go to /groups
and the html page refreshes ok with no need to logout/login

**Comment by george-hawkins-aa** [comment] 2016-08-26 08:54
Hello @mzumbadoate - I'm impressed you got my old Stormpath project running with 1.0.3 as it involved quite a lot of issues unrelated to this one and involved some heavy battering at the internals of the SDK - the kind of areas that have changed a lot since I wrote it in December 2015.

First - if you used my project (in it's original form using stormpath-default-spring-boot-starter 1.0.RC7.1) you should indeed have been able to add/remove groups without needing to log in or out. The project demonstrates that this is possible but only if you sneak in and access internals of the SDK. This sneaking is done in my class [`GroupService.java`](https://github.com/george-hawkins-aa/stormpath-spring-boot-example/blob/master/src/main/java/hello/GroupService.java) where I use reflection to get at a private method of the SDK - see the use of `getGrantedAuthorities` and the implementation of `getMethod()`.

So my project is demonstrating that I can indeed achieve the behavior I want (without needing to log in or out) but only by hacking the SDK. And this ticket was about trying to make that hacking step unnecessary.

It may be that other changes to the SDK in the meantime mean that this has all been resolved, by changes elsewhere that weren't made specifically in response to this tickets, but unfortunately I'm in late product development at the moment and we're all rather overstretched here so I can't check this out personally 😞 

If you say that you just had to copy over my `groups.html` and `GroupsController.java` files to a clean 1.0.3 project _without_ needing the hacky `GroupService.java` logic then it sounds like things have indeed been resolved.

**Comment by mzumbadoate** [comment] 2016-08-30 15:51
since this is true
> If you say that you just had to copy over my groups.html and GroupsController.java files to a clean 1.0.3 project without needing the hacky GroupService.java logic then it sounds like things have indeed been resolved.

I'm closing this ticket

**Closed by mzumbadoate** 2016-08-30 15:51 UTC
Labels: in progress
