### ISSUE TITLE
AuthenticationRequest should have a way to specify AccountOptions

### ISSUE THREAD

**Issue by lhazlewood** [stormpath/stormpath-sdk-java#99] opened 2014-08-29 16:04 UTC
To allow the user to customize the returned account resource (e.g. resource expansion)

**Comment by mrioan** [comment] 2015-07-16 15:48
Closing as this is a duplicate of https://github.com/stormpath/stormpath-sdk-java/issues/11

**Closed by mrioan** 2015-07-16 15:48 UTC
