### ISSUE TITLE
Disabling account cookie and enabling session storage fails

### ISSUE THREAD

**Issue by lhazlewood** [stormpath/stormpath-sdk-java#422] opened 2015-12-22 20:32 UTC
If you want to enable session storage for authenticated accounts and disable cookie usage, e.g.

```properties
stormpath.web.authc.savers.cookie.enabled = false
stormpath.web.authc.savers.session.enabled = true
```

this fails due to `HttpServletRequest.getAuthType` failing:

```
java.lang.IllegalArgumentException: An authenticated account must be represented with a specific request authType.  This must be set by a Resolver<Account> on account discovery or immediately after login.  This is an implementation bug and should be reported.
	at com.stormpath.sdk.lang.Assert.hasText(Assert.java:130) ~[classes/:na]
	at com.stormpath.sdk.servlet.http.impl.StormpathHttpServletRequest.getAuthType(StormpathHttpServletRequest.java:321) ~[classes/:na]
	at com.stormpath.sdk.servlet.filter.account.AccountResolverFilter.filter(AccountResolverFilter.java:118) ~[classes/:na]
```

**Comment by waxmihs2902** [comment] 2015-12-25 01:06
thanks! tryin to pull

**Comment by jarias** [comment] 2016-03-11 16:34
@lhazlewood looks like we configure the servlet plugin differently, do we want to standardize using those 2 properties?

```
# The storage locations that should be used to save account state after successful authentication.
# The value must be the name of a name stormpath.web.authc.savers.NAME_HERE definition
#
# The value is a comma-delimited list of one or more of cookie, session, or disabled:
#
# cookie:   Store the account state in a cookie.  The cookie's settings are controlled by the
#           stormpath.web.account.cookie.* properties below.  The same cookie is read later when the
#           stormpath.web.account.resolvers property contains a 'cookie' value (without the quotes).
#
# session:  Store the account state in the servlet HTTP session.  This option will create a new HTTP session if one
#           does not yet exist.
#
# disabled: Do not store the account state during a request.  This is a good option if your server-side app
#           authenticates every request (for example, a REST API).
#
stormpath.web.authc.savers = cookie
```

**Comment by jarias** [comment] 2016-03-11 16:45
I'm closing this ticket since the original report is not reproducible anymore

**Closed by jarias** 2016-03-11 16:45 UTC
Labels: bug, in progress
