### ISSUE TITLE
Collection Resources metadata not updated

### ISSUE THREAD

**Issue by antollinim** [stormpath/stormpath-sdk-java#160] opened 2015-03-23 15:27 UTC
Collection Resources metadata (offset, limit) are not being updated when re-retrieving an already materialized collection resource. This is not a cache issue, this is an unwanted materialization for internal collection resources properties.

**Comment by lhazlewood** [comment] 2015-04-01 18:00
Closing per the 1.0.RC4 release

**Closed by lhazlewood** 2015-04-01 18:00 UTC

**Comment by lhazlewood** [comment] 2015-05-19 18:11
@mrioan I'm working on a problem where I need a Collection resource in Map form to be swapped out to an actual CollectionResource instance.  This is to ensure that already-in-memory data can be accessed directly instead of forcing another request to the API server.

This requires changing the following lines in AbstractResource:

```java
//replace the existing link object (map with an href) with the newly constructed Resource instance.
//Don't dirty the instance - we're just swapping out a property that already exists for the materialized version.
//let's not materialize internal collection resources, so they are always retrieved from the backend: https://github.com/stormpath/stormpath-sdk-java/issues/160
if (!CollectionResource.class.isAssignableFrom(clazz)) {
    setProperty(key, resource, false);
}
```
to become just 

```java
setProperty(key, resource, false);
```

But as you can see there is a comment that references this issue as to why it is prevented when the resource is a collection.

Do you have any insight as to why this was required?  If I change the code as suspected, what are the side effects?

**Comment by lhazlewood** [comment] 2015-05-19 18:18
When the comment was made back to this issue - is the problem that a materialized CollectionResource, when retrieved twice, does not reflect the first page of the collection?

In other words:

```java
AccountList accounts = application.getAccounts();
//get one page of accounts, but short circuit all remaining pages

//does 'accounts2' reflect the first page? Or the last page from 'accounts' iteration?
AccountsList accounts2 = application.getAccounts();
```

**Comment by mrioan** [comment] 2015-05-19 18:30
@lhazlewood the problem that this code fixed was that Collection metadata was not being re-retrieved, only the collection data. This was not a problem until we introduced the `size` property. Pseudo-coding here:

```
AccountList accounts = application.getAccounts(); //*1
assertTrue(accounts.size == 10) //ok

application.createAccount(newAccount);
accounts = application.getAccounts();
assertTrue(accounts.size == 11) //failed, reported size is 10. The application already contained the meta-data of the list from step *1 (ie. size=10). The list contains 11 items when traversing the list though. The problem is only in the materialized metadata.

**Comment by lhazlewood** [comment] 2015-05-19 18:37
Got it - thanks.  Perhaps one solution is to invalidate the local in-memory reference if we add an account.  The trouble is what to do when you delete an account - any collection that references the deleted account should not reflect that account.
